In [1]:
import xarray as xr
import numpy as np
import netCDF4
import pandas as pd
from scipy import signal

In [2]:
var = "ahfl"
arr = []
for ens_index in range(1,17):
        filename = "/work/uo1075/u241321/data/u241321/data_cdo/ahfl_assi/"+var+"_Amon_MPI-ESM-LR_asSEIKERAf_r"+str(ens_index)+"i8p4_197001-201912_ym_g1d0.nc"
        arr.append(xr.load_dataset(filename,decode_times=False).assign_coords(ensemble=ens_index))

In [3]:
data = xr.concat(arr, dim="member")

In [4]:
annual_pre = data [var]

In [5]:
annual_prediction = annual_pre.transpose("time", "member", "lat", "lon") # 

In [6]:
dat = np.mean(annual_prediction,axis=0)
dif = annual_prediction
dat

<xarray.DataArray 'ahfl' (member: 16, lat: 180, lon: 360)>
array([[[ 0.11640331,  0.1164064 ,  0.1217877 , ...,  0.10597709,
          0.11107412,  0.11107717],
        [ 0.09571215,  0.09752319,  0.09931197, ...,  0.09208554,
          0.09349697,  0.09437009],
        [-0.1679583 , -0.1833783 , -0.19818856, ..., -0.11526456,
         -0.13299905, -0.15116523],
        ...,
        [-4.205835  , -4.2081494 , -4.208272  , ..., -4.2099714 ,
         -4.2080455 , -4.2058    ],
        [-4.027304  , -4.026444  , -4.0246096 , ..., -4.037392  ,
         -4.035206  , -4.0302243 ],
        [-4.0151963 , -4.015193  , -4.0107718 , ..., -4.023472  ,
         -4.019508  , -4.0195045 ]],

       [[ 0.11755225,  0.11755549,  0.12257243, ...,  0.10669299,
          0.1121768 ,  0.11218004],
        [ 0.09717168,  0.0992884 ,  0.10096029, ...,  0.09278794,
          0.09424706,  0.09549122],
        [-0.16475523, -0.18060966, -0.19573435, ..., -0.11373527,
         -0.13057624, -0.1480774 ],
...
        [-4.361984  , -4.361893  , -4.3609133 , ..., -4.3721266 ,
         -4.3679333 , -4.3639975 ],
        [-4.120548  , -4.1203814 , -4.1185594 , ..., -4.1315794 ,
         -4.1276345 , -4.122965  ],
        [-4.103899  , -4.1038957 , -4.0985546 , ..., -4.1132603 ,
         -4.109175  , -4.109171  ]],

       [[ 0.11791839,  0.11792129,  0.12288909, ...,  0.10833829,
          0.11307294,  0.1130758 ],
        [ 0.09786718,  0.0992085 ,  0.10061775, ...,  0.09418129,
          0.09537211,  0.0965884 ],
        [-0.1645734 , -0.17979795, -0.19487584, ..., -0.1114774 ,
         -0.12938623, -0.14776951],
        ...,
        [-4.4027815 , -4.3999085 , -4.3964934 , ..., -4.4075813 ,
         -4.4067187 , -4.4050517 ],
        [-4.1872854 , -4.184525  , -4.1815777 , ..., -4.191652  ,
         -4.189431  , -4.1889215 ],
        [-4.1693206 , -4.169318  , -4.1651244 , ..., -4.178487  ,
         -4.1738386 , -4.1738377 ]]], dtype=float32)
Coordinates:
  * lon       (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * lat       (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
    ensemble  (member) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Dimensions without coordinates: member

In [7]:
annual_prediction

<xarray.DataArray 'ahfl' (time: 50, member: 16, lat: 180, lon: 360)>
array([[[[ 0.08182196,  0.08182285,  0.08323505, ...,  0.07984255,
           0.0809117 ,  0.08091246],
         [ 0.06339532,  0.06525355,  0.06465115, ...,  0.06656423,
           0.06513403,  0.06335548],
         [-0.17129138, -0.18765837, -0.20726517, ..., -0.12249231,
          -0.14198032, -0.15606536],
         ...,
         [-4.2422447 , -4.2387757 , -4.2406936 , ..., -4.254136  ,
          -4.250161  , -4.24604   ],
         [-4.1060624 , -4.0943727 , -4.0869317 , ..., -4.1179943 ,
          -4.113729  , -4.1125145 ],
         [-4.088703  , -4.0886955 , -4.07888   , ..., -4.111492  ,
          -4.1004972 , -4.100491  ]],

        [[ 0.08766022,  0.08766135,  0.089164  , ...,  0.08475987,
           0.08649253,  0.08649379],
         [ 0.070407  ,  0.07094815,  0.07011132, ...,  0.07030195,
           0.06960759,  0.06996015],
         [-0.17409357, -0.1904137 , -0.20585136, ..., -0.12037081,
          -0.13701378, -0.1562936 ],
...
         [-4.958134  , -4.940442  , -4.9161534 , ..., -4.9932175 ,
          -4.980858  , -4.971606  ],
         [-4.922061  , -4.915472  , -4.903621  , ..., -4.9226894 ,
          -4.9231434 , -4.924618  ],
         [-4.9092903 , -4.9092836 , -4.907884  , ..., -4.918707  ,
          -4.9171305 , -4.91713   ]],

        [[ 0.03888397,  0.03888917,  0.04818029, ...,  0.02512093,
           0.03043132,  0.0304345 ],
         [ 0.018394  ,  0.02221844,  0.02818041, ...,  0.01740666,
           0.01842718,  0.01713025],
         [-0.17713362, -0.19655822, -0.20943633, ..., -0.11917832,
          -0.13994336, -0.158262  ],
         ...,
         [-4.99727   , -4.990071  , -4.990493  , ..., -5.0281625 ,
          -5.016167  , -5.0059686 ],
         [-4.8958316 , -4.8909287 , -4.8964734 , ..., -4.9135756 ,
          -4.9061007 , -4.900889  ],
         [-4.8944774 , -4.894478  , -4.8878274 , ..., -4.9107604 ,
          -4.8972077 , -4.897201  ]]]], dtype=float32)
Coordinates:
  * time      (time) float64 149.5 161.5 173.5 185.5 ... 701.5 713.5 725.5 737.5
  * lon       (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * lat       (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
    ensemble  (member) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Dimensions without coordinates: member
Attributes:
    standard_name:  ahfl
    long_name:      var147 aka ahfl
    units:          W m-2
    code:           147
    table:          128

In [33]:
dropped = dif.stack(feature=("member","lat","lon")).dropna(dim="feature")
detrend = signal.detrend(dropped ,axis=0)
feature = dropped .coords["feature"]
time = dropped .coords["time"]
detrend = xr.DataArray(detrend, dims = ["time","feature"], coords = {"time":time,"feature":feature}).unstack()

In [36]:
detrend.to_netcdf("/work/uo1075/u241321/data/ahfl_1970-2019_assi_dt.nc")

In [37]:
# full_value
dif.to_netcdf("/work/uo1075/u241321/data/ahfl_1970-2019_assi_full_value.nc")

In [8]:
aa = annual_prediction - dat
aa.to_netcdf("/work/uo1075/u241321/data/ahfl_1970-2019_assi.nc")


<xarray.DataArray 'ahfl' (time: 50, member: 16, lat: 180, lon: 360)>
array([[[[-3.45813483e-02, -3.45835462e-02, -3.85526493e-02, ...,
          -2.61345431e-02, -3.01624238e-02, -3.01647112e-02],
         [-3.23168263e-02, -3.22696418e-02, -3.46608162e-02, ...,
          -2.55213082e-02, -2.83629373e-02, -3.10146064e-02],
         [-3.33307683e-03, -4.28007543e-03, -9.07661021e-03, ...,
          -7.22774863e-03, -8.98127258e-03, -4.90012765e-03],
         ...,
         [-3.64098549e-02, -3.06262970e-02, -3.24215889e-02, ...,
          -4.41646576e-02, -4.21156883e-02, -4.02398109e-02],
         [-7.87582397e-02, -6.79287910e-02, -6.23221397e-02, ...,
          -8.06021690e-02, -7.85231590e-02, -8.22901726e-02],
         [-7.35068321e-02, -7.35025406e-02, -6.81080818e-02, ...,
          -8.80203247e-02, -8.09893608e-02, -8.09864998e-02]],

        [[-2.98920348e-02, -2.98941433e-02, -3.34084332e-02, ...,
          -2.19331235e-02, -2.56842673e-02, -2.56862491e-02],
         [-2.67646760e-02, -2.83402577e-02, -3.08489725e-02, ...,
          -2.24859938e-02, -2.46394724e-02, -2.55310610e-02],
         [-9.33834910e-03, -9.80404019e-03, -1.01170093e-02, ...,
          -6.63554668e-03, -6.43754005e-03, -8.21620226e-03],
...
          -6.21090889e-01, -6.12924576e-01, -6.07608318e-01],
         [-8.01513195e-01, -7.95090675e-01, -7.85061836e-01, ...,
          -7.91110039e-01, -7.95508862e-01, -8.01652908e-01],
         [-8.05391312e-01, -8.05387974e-01, -8.09329510e-01, ...,
          -8.05446625e-01, -8.07955265e-01, -8.07959080e-01]],

        [[-7.90344179e-02, -7.90321231e-02, -7.47088045e-02, ...,
          -8.32173526e-02, -8.26416239e-02, -8.26412961e-02],
         [-7.94731826e-02, -7.69900680e-02, -7.24373385e-02, ...,
          -7.67746344e-02, -7.69449323e-02, -7.94581473e-02],
         [-1.25602186e-02, -1.67602748e-02, -1.45604908e-02, ...,
          -7.70092010e-03, -1.05571300e-02, -1.04924887e-02],
         ...,
         [-5.94488621e-01, -5.90162277e-01, -5.93999386e-01, ...,
          -6.20581150e-01, -6.09448433e-01, -6.00916862e-01],
         [-7.08546162e-01, -7.06403732e-01, -7.14895725e-01, ...,
          -7.21923828e-01, -7.16669559e-01, -7.11967468e-01],
         [-7.25156784e-01, -7.25159645e-01, -7.22702980e-01, ...,
          -7.32273579e-01, -7.23369122e-01, -7.23363400e-01]]]],
      dtype=float32)
Coordinates:
  * time      (time) float64 149.5 161.5 173.5 185.5 ... 701.5 713.5 725.5 737.5
  * lon       (lon) float64 -179.5 -178.5 -177.5 -176.5 ... 177.5 178.5 179.5
  * lat       (lat) float64 -89.5 -88.5 -87.5 -86.5 ... 86.5 87.5 88.5 89.5
    ensemble  (member) int64 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16
Dimensions without coordinates: member